/**
 * Results Screen Test - Single Player
 * PRD Reference: Section 4.7 - Results Screen
 *
 * Test page to verify ResultsSinglePlayer component with mock data
 */

import { ResultsSinglePlayer } from './ResultsSinglePlayer';
import type { GameSession } from '../../types';

export function ResultsTestSingle() {
  // Mock game session data for testing
  const mockSession: GameSession = {
    id: 'test-session-001',
    categoryId: 1,
    categoryName: 'Test Kategorisi',
    categoryEmoji: '📚',
    mode: 'single',
    state: 'finished',
    participants: [
      {
        name: 'Test Oyuncusu',
        type: 'player',
        score: 2100,
        wordsFound: 8,
        wordsSkipped: 3,
        lettersRevealed: 12,
        currentWordIndex: 11,
        isActive: true,
        elapsedTimeSeconds: 180, // 3 minutes used
        totalTimeSeconds: 300, // 5 minutes total
        words: [
          {
            id: 1,
            word: 'KEDI',
            hint: 'Miyavlayan evcil hayvan',
            letterCount: 4,
            letters: [
              { char: 'K', status: 'revealed', index: 0 },
              { char: 'E', status: 'revealed', index: 1 },
              { char: 'D', status: 'revealed', index: 2 },
              { char: 'İ', status: 'revealed', index: 3 },
            ],
            remainingGuesses: 2,
            lettersRevealed: 0,
            hasMadeGuess: true,
            result: 'found',
            pointsEarned: 400,
          },
          {
            id: 2,
            word: 'KAPI',
            hint: 'Odaya girdiğimiz yer',
            letterCount: 4,
            letters: [
              { char: 'K', status: 'revealed', index: 0 },
              { char: 'A', status: 'revealed', index: 1 },
              { char: 'P', status: 'revealed', index: 2 },
              { char: 'I', status: 'revealed', index: 3 },
            ],
            remainingGuesses: 2,
            lettersRevealed: 1,
            hasMadeGuess: true,
            result: 'found',
            pointsEarned: 300,
          },
          {
            id: 3,
            word: 'KALEM',
            hint: 'Yazı yazmak için kullanılır',
            letterCount: 5,
            letters: [
              { char: 'K', status: 'revealed', index: 0 },
              { char: 'A', status: 'revealed', index: 1 },
              { char: 'L', status: 'hidden', index: 2 },
              { char: 'E', status: 'hidden', index: 3 },
              { char: 'M', status: 'hidden', index: 4 },
            ],
            remainingGuesses: 0,
            lettersRevealed: 2,
            hasMadeGuess: true,
            result: 'skipped',
            pointsEarned: 0,
          },
          {
            id: 4,
            word: 'MASA',
            hint: 'Üzerinde yemek yediğimiz yer',
            letterCount: 4,
            letters: [
              { char: 'M', status: 'revealed', index: 0 },
              { char: 'A', status: 'revealed', index: 1 },
              { char: 'S', status: 'revealed', index: 2 },
              { char: 'A', status: 'revealed', index: 3 },
            ],
            remainingGuesses: 1,
            lettersRevealed: 2,
            hasMadeGuess: true,
            result: 'found',
            pointsEarned: 200,
          },
          {
            id: 5,
            word: 'SANDALYE',
            hint: 'Üzerine oturduğumuz şey',
            letterCount: 8,
            letters: [
              { char: 'S', status: 'revealed', index: 0 },
              { char: 'A', status: 'revealed', index: 1 },
              { char: 'N', status: 'revealed', index: 2 },
              { char: 'D', status: 'revealed', index: 3 },
              { char: 'A', status: 'revealed', index: 4 },
              { char: 'L', status: 'revealed', index: 5 },
              { char: 'Y', status: 'revealed', index: 6 },
              { char: 'E', status: 'revealed', index: 7 },
            ],
            remainingGuesses: 2,
            lettersRevealed: 0,
            hasMadeGuess: true,
            result: 'found',
            pointsEarned: 800,
          },
          {
            id: 6,
            word: 'BILGISAYAR',
            hint: 'Elektronik cihaz',
            letterCount: 10,
            letters: [
              { char: 'B', status: 'revealed', index: 0 },
              { char: 'İ', status: 'hidden', index: 1 },
              { char: 'L', status: 'hidden', index: 2 },
              { char: 'G', status: 'hidden', index: 3 },
              { char: 'İ', status: 'hidden', index: 4 },
              { char: 'S', status: 'hidden', index: 5 },
              { char: 'A', status: 'hidden', index: 6 },
              { char: 'Y', status: 'hidden', index: 7 },
              { char: 'A', status: 'hidden', index: 8 },
              { char: 'R', status: 'hidden', index: 9 },
            ],
            remainingGuesses: 0,
            lettersRevealed: 1,
            hasMadeGuess: true,
            result: 'skipped',
            pointsEarned: 0,
          },
          {
            id: 7,
            word: 'KITAP',
            hint: 'Okumak için kullanılır',
            letterCount: 5,
            letters: [
              { char: 'K', status: 'revealed', index: 0 },
              { char: 'İ', status: 'revealed', index: 1 },
              { char: 'T', status: 'revealed', index: 2 },
              { char: 'A', status: 'revealed', index: 3 },
              { char: 'P', status: 'revealed', index: 4 },
            ],
            remainingGuesses: 3,
            lettersRevealed: 0,
            hasMadeGuess: true,
            result: 'found',
            pointsEarned: 500,
          },
          {
            id: 8,
            word: 'TELEFON',
            hint: 'Konuşmak için kullanılan cihaz',
            letterCount: 7,
            letters: [
              { char: 'T', status: 'revealed', index: 0 },
              { char: 'E', status: 'revealed', index: 1 },
              { char: 'L', status: 'revealed', index: 2 },
              { char: 'E', status: 'revealed', index: 3 },
              { char: 'F', status: 'revealed', index: 4 },
              { char: 'O', status: 'revealed', index: 5 },
              { char: 'N', status: 'revealed', index: 6 },
            ],
            remainingGuesses: 1,
            lettersRevealed: 3,
            hasMadeGuess: true,
            result: 'found',
            pointsEarned: 400,
          },
          {
            id: 9,
            word: 'ARABA',
            hint: 'Taşıt aracı',
            letterCount: 5,
            letters: [
              { char: 'A', status: 'revealed', index: 0 },
              { char: 'R', status: 'hidden', index: 1 },
              { char: 'A', status: 'hidden', index: 2 },
              { char: 'B', status: 'hidden', index: 3 },
              { char: 'A', status: 'hidden', index: 4 },
            ],
            remainingGuesses: 0,
            lettersRevealed: 1,
            hasMadeGuess: true,
            result: 'skipped',
            pointsEarned: 0,
          },
          {
            id: 10,
            word: 'GÖZLÜK',
            hint: 'Görmek için takılan',
            letterCount: 6,
            letters: [
              { char: 'G', status: 'revealed', index: 0 },
              { char: 'Ö', status: 'revealed', index: 1 },
              { char: 'Z', status: 'revealed', index: 2 },
              { char: 'L', status: 'revealed', index: 3 },
              { char: 'Ü', status: 'revealed', index: 4 },
              { char: 'K', status: 'revealed', index: 5 },
            ],
            remainingGuesses: 2,
            lettersRevealed: 1,
            hasMadeGuess: true,
            result: 'found',
            pointsEarned: 500,
          },
          {
            id: 11,
            word: 'SAAT',
            hint: 'Zamanı gösteren',
            letterCount: 4,
            letters: [
              { char: 'S', status: 'revealed', index: 0 },
              { char: 'A', status: 'revealed', index: 1 },
              { char: 'A', status: 'revealed', index: 2 },
              { char: 'T', status: 'revealed', index: 3 },
            ],
            remainingGuesses: 3,
            lettersRevealed: 0,
            hasMadeGuess: true,
            result: 'found',
            pointsEarned: 400,
          },
        ],
      },
    ],
    activeParticipantIndex: 0,
    totalTimeSeconds: 300,
    elapsedTimeSeconds: 243, // 4:03 elapsed
    isPaused: false,
    startedAt: new Date(Date.now() - 243000).toISOString(),
    finishedAt: new Date().toISOString(),
  };

  const handlePlayAgain = () => {
    console.log('Play Again clicked');
  };

  return <ResultsSinglePlayer session={mockSession} onPlayAgain={handlePlayAgain} />;
}
